fix "no viable alternative at input 'WITH'"
red-soft-ru/shardingsphere pull request #67
Opened 2024-07-03 11:10 UTC by makssent

Fixes #40.

Changes proposed in this pull request:
 "Add support for WITH()"
 New error message: "Table or view `T121` does not exist."

---

2024-07-03 13:43 UTC, romansimakov reviewed
А зачем ты лицензию удалил?

2024-07-03 14:38 UTC, makssent commented
В отдельном проекте своём работаю с файлами грамматик чтобы понять всю внутрянку, оттуда скопировал весь код и закинул в форк, протестировал, посмотрел что все заработало и забыл проверить на лицензию ( точнее вообще не думал о ней ), поправил варнинги которые были и отправил

2024-07-04 17:31 UTC, TedCraft requested changes
В целом всё ок, но как по мне стоит убрать блок 
dmlStatement
    : insert
    | update
    | delete
    | select
    ;
Он нигде не используется и как по мне его можно удалить.

2024-07-04 17:38 UTC, makssent commented
Тоже об этом подумал когда уже залил, не стал откатывать

2024-07-08 15:06 UTC, TedCraft requested changes
Комментарии пофикшены не совсем правильно. У тебя комментарий в реализации является токеном, когда по хорошему он должен игнорироваться. Там в файлах с грамматиками есть файл Comments.g4, в нём и описывается правило для обработки комментариев, надо просто посмотреть что там с ним не так. И надо запулить коммит с удалённым dmlStatement, что бы можно было файл без лишнего содержимого смерджить.

2024-07-08 18:20 UTC, makssent commented
Увидел, хорошо

2024-07-24 18:56 UTC, TedCraft approved these changes

2024-07-24 20:42 UTC, merged